[package]
name = "lean-model-categories"
version = "0.1"
lean_version = "3.4.2"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover/mathlib", rev = "3dc9935aad61ce539c7a0b98f3c20f41607ae159"}
lean-homotopy-theory = {git = "https://github.com/rwbarton/lean-homotopy-theory", rev = "a38c8bdf8093435a1ee9bbd85e24348b85069e42"}
